package com.assistant.core.ai.data

/**
 * Raw prompt data generated by PromptManager
 * Contains system prompt levels and session messages
 * Provider transforms this according to its specific API requirements
 *
 * Note: Level 3 has been removed - AI now uses APP_STATE command when needed
 */
data class PromptData(
    val level1Content: String,     // System documentation (with AI limits)
    val level2Content: String,     // User data (always_send tools)
    val sessionMessages: List<SessionMessage>  // Raw messages for history
)
