package com.assistant.core.ai.data

/**
 * Raw prompt data generated by PromptManager
 * Contains system prompt levels and session messages
 * Provider transforms this according to its specific API requirements
 */
data class PromptData(
    val level1Content: String,     // System documentation (with AI limits)
    val level2Content: String,     // User data (always_send tools)
    val level3Content: String,     // Application state (zones, tools configs)
    val sessionMessages: List<SessionMessage>  // Raw messages for history
)
