package com.assistant.core.database.entities

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Log entry entity for in-app error logging and debugging
 *
 * Stores all logs generated by LogManager for debugging purposes.
 * Logs are displayed in LogsScreen with filters by level and time range.
 *
 * @property id Unique identifier (auto-generated)
 * @property timestamp Timestamp when log was created (millis since epoch)
 * @property level Log level (DEBUG, INFO, WARN, ERROR)
 * @property tag Log tag/category (e.g., "AI_SERVICE", "SCHEMA", "DATABASE")
 * @property message Log message
 * @property throwableMessage Stack trace message if throwable was provided, null otherwise
 */
@Entity(
    tableName = "log_entries",
    indices = [Index(value = ["timestamp"])]
)
data class LogEntry(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val timestamp: Long,
    val level: String,
    val tag: String,
    val message: String,
    val throwableMessage: String? = null
)
