package com.assistant.core.versioning

import android.content.Context
import android.content.SharedPreferences

/**
 * Application version and install tracking
 *
 * Simplified to only track first launch state.
 * Version numbers come from BuildConfig (generated by Gradle).
 *
 * Architecture:
 * - BuildConfig.VERSION_CODE: App version for comparisons (build.gradle versionCode)
 * - BuildConfig.VERSION_NAME: Human-readable version (build.gradle versionName)
 * - AppDatabase.VERSION: Database schema version (independent from app version)
 */
class AppVersionManager(private val context: Context) {

    private val prefs: SharedPreferences = context.getSharedPreferences("app_version", Context.MODE_PRIVATE)

    companion object {
        private const val PREF_FIRST_LAUNCH = "first_launch"
    }

    /**
     * Check if this is the first app launch
     * Used for initial setup, onboarding, or default data
     */
    fun isFirstLaunch(): Boolean {
        return prefs.getBoolean(PREF_FIRST_LAUNCH, true)
    }

    /**
     * Mark first installation as complete
     * Should be called after successful initial setup
     */
    fun markFirstLaunchComplete() {
        prefs.edit().putBoolean(PREF_FIRST_LAUNCH, false).apply()
    }
}
