package app.treelune.core.ai.validation

import app.treelune.core.ai.data.DataCommand

/**
 * Context for AI action validation containing all information needed for the UI
 *
 * This context is generated by ValidationResolver and passed to the UI for display.
 * For persistence simplicity, only aiMessageId is stored in DB - the full context
 * is reconstructed on app restart by re-running ValidationResolver.shouldValidate()
 *
 * @param aiMessageId ID of the AI message containing the actions (for reconstruction after app restart)
 * @param actions ALL actions to execute (both validated and non-validated)
 * @param verbalizedActions Human-readable descriptions with validation reasons
 */
data class ValidationContext(
    val aiMessageId: String,
    val actions: List<DataCommand>,
    val verbalizedActions: List<VerbalizedAction>
)

/**
 * Verbalized action with validation metadata
 *
 * Each action in the validation UI is displayed with:
 * - Its human-readable description (e.g., "Création de la zone \"Santé\"")
 * - A warning icon if validated by CONFIG (sensitive action)
 * - The validation reason explaining why validation is required
 *
 * Actions with validationReason = null are displayed without reason (review list)
 *
 * @param actionId ID of the DataCommand this describes
 * @param description Human-readable action description (substantive form)
 * @param requiresWarning true when a protection or the session asks for it (not the AI alone): shows the warning icon
 * @param validationReason Reason for validation (null if action doesn't require validation by itself)
 * @param entries The entries the action writes, by their fields; none for other actions
 * @param entriesError Why the entries could not be shown, when a value the AI gave does not read
 */
data class VerbalizedAction(
    val actionId: String,
    val description: String,
    val requiresWarning: Boolean,
    val validationReason: String?,
    val entries: List<ProposedEntry> = emptyList(),
    val entriesError: String? = null
)
